### ISSUE TITLE
Latex not found by python scripts to generate figures

### ISSUE THREAD

**Issue by mathren** [rodluger/showyourwork#45]
I have a setup that successfully builds locally on my machine, but on the github CI the script producing my figures fails because:
``` RuntimeError: Failed to process string with tex because latex could not be found```

Below is the full traceback, which seems to indicate the cause of the above issue is

``` FileNotFoundError: [Errno 2] No such file or directory: 'latex'```

Not sure how I can fix this. I do have a custom matplotlibrc but that should not be an issue.

Full traceback:
```
   Traceback (most recent call last):
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/texmanager.py", line 252, in _run_checked_subprocess
      report = subprocess.check_output(
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/subprocess.py", line 424, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/subprocess.py", line 505, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/subprocess.py", line 951, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/subprocess.py", line 1821, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'latex'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/src/figures/fit_DM_PPI.py", line 107, in <module>
      plt.savefig('fit_DM_PPI.pdf')
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/pyplot.py", line 966, in savefig
      res = fig.savefig(*args, **kwargs)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/figure.py", line 3015, in savefig
      self.canvas.print_figure(fname, **kwargs)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2230, in print_figure
      self.figure.draw(renderer)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
      result = draw(artist, renderer, *args, **kwargs)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/figure.py", line 2784, in draw
      self.tight_layout(**self._tight_parameters)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/figure.py", line 3164, in tight_layout
      kwargs = get_tight_layout_figure(
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/tight_layout.py", line 312, in get_tight_layout_figure
      kwargs = auto_adjust_subplotpars(fig, renderer,
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/tight_layout.py", line 84, in auto_adjust_subplotpars
      bb += [ax.get_tightbbox(renderer, for_layout_only=True)]
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 4439, in get_tightbbox
      bb_yaxis = self.yaxis.get_tightbbox(
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/axis.py", line 1088, in get_tightbbox
      self._update_label_position(renderer)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/axis.py", line 2359, in _update_label_position
      bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/axis.py", line 1873, in _get_tick_boxes_siblings
      tlb, tlb2 = axis._get_tick_bboxes(ticks_to_draw, renderer)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/axis.py", line 1068, in _get_tick_bboxes
      return ([tick.label1.get_window_extent(renderer)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/axis.py", line 1068, in <listcomp>
      return ([tick.label1.get_window_extent(renderer)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/text.py", line 903, in get_window_extent
      bbox, info, descent = self._get_layout(self._renderer)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/text.py", line 306, in _get_layout
      _, lp_h, lp_d = renderer.get_text_width_height_descent(
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/backends/_backend_pdf_ps.py", line 88, in get_text_width_height_descent
      w, h, d = texmanager.get_text_width_height_descent(
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/texmanager.py", line 399, in get_text_width_height_descent
      dvifile = self.make_dvi(tex, fontsize)
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/texmanager.py", line 291, in make_dvi
      self._run_checked_subprocess(
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/conda/f43b19a9d6108173bf006e7a97638d9e/lib/python3.9/site-packages/matplotlib/texmanager.py", line 256, in _run_checked_subprocess
      raise RuntimeError(
  RuntimeError: Failed to process string with tex because latex could not be found
  Traceback (most recent call last):
  make[1]: Leaving directory '/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/showyourwork'
    File "/home/runner/work/top_down_compact_obj_mass/top_down_compact_obj_mass/.snakemake/scripts/tmpqvjl1p9p.figure.py", line 83, in <module>
  Error: exec: sysctl: cannot stat /proc/sys/machdep/cpu/brand_string: No such file or directory
  ```

**Comment by rodluger** [comment]
``showyourwork`` uses ``tectonic`` to build the TeX document (instead of a full LaTeX distribution). You probably have a LaTeX distribution locally, which is why ``matplotlib`` can run ``latex`` internally to compile the math-mode TeX in your figures; but ``latex`` is not installed on the GitHub Actions runner, causing the error you're seeing.

You have two options: set ``rcParams["text.usetex"]`` to ``False`` (and rely on ``matplotlib``'s own math text to render strings), or install a full LaTeX distribution as part of your workflow. This would entail adding a step to the ``.github/workflows/showyourwork.yml`` file where you explicitly download and install a TeX distribution (something like https://github.com/yihui/tinytex/ perhaps), which will ensure ``python`` can find a working ``latex`` command.

**Comment by rodluger** [comment]
Just to follow up on this, matplotlib's mathtext is usually all you need: https://matplotlib.org/stable/tutorials/text/mathtext.html

I recommend installing the LaTeX distribution only if you _really_ need it (i.e., your figure labels contain complicated math expressions or highly customized TeX typesetting).

**Comment by mathren** [comment]
Thank you! Got it, using mathtext in matplotlib works as I want once I fiddled a bit with the fonts!

**Comment by rodluger** [comment]
@mathren I caved and implemented your original request. Now you can ask `showyourwork` to install a minimal TeX distribution if you specify `install-tex` in the `.github/workflows/showyourwork.yml` file. Check out the docs here: https://showyourwork.readthedocs.io/en/stable/custom/#figures-that-require-latex

I still recommend _not_ setting `usetex` unless you need it, though.

**Comment by mathren** [comment]
Fantastic! I will still follow your recommendation, but the updated docs look great
