### ISSUE TITLE
Strange errors with Zenodo upload attempts

### ISSUE THREAD

**Issue by arm61** [rodluger/showyourwork#51]
When I push to Zenodo some (large) datasets that scripts in my workflow produce, I get some strange errors that I cannot pin down. They seem to be either 
```
Traceback (most recent call last):
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/scripts/tmpymlz6v47.zenodo.py", line 329, in <module>
    upload_simulation(
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/scripts/tmpymlz6v47.zenodo.py", line 144, in upload_simulation
    r = check_status(
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/scripts/tmpymlz6v47.zenodo.py", line 21, in check_status
    data = r.json()
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

or 

```
Traceback (most recent call last):
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/scripts/tmpy2adhavi.zenodo.py", line 329, in <module>
    upload_simulation(
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/scripts/tmpy2adhavi.zenodo.py", line 145, in upload_simulation
    requests.post(
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/andrewmccluskey/anaconda3/envs/msd-error/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/conda/52b8b44ac1fc2296e8e9f1f2c6621990/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/conda/52b8b44ac1fc2296e8e9f1f2c6621990/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/conda/52b8b44ac1fc2296e8e9f1f2c6621990/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/conda/52b8b44ac1fc2296e8e9f1f2c6621990/lib/python3.9/http/client.py", line 1073, in _send_output
    self.send(chunk)
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/conda/52b8b44ac1fc2296e8e9f1f2c6621990/lib/python3.9/http/client.py", line 995, in send
    self.sock.sendall(data)
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/conda/52b8b44ac1fc2296e8e9f1f2c6621990/lib/python3.9/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/Users/andrewmccluskey/work/research/msd-errors/.snakemake/conda/52b8b44ac1fc2296e8e9f1f2c6621990/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes
```

Any tips for debugging?

**Comment by rodluger** [comment]
How big are the files? I'll play around with this tomorrow.

**Comment by arm61** [comment]
The first error message is returned for two files that are 500 MB and 900 MB. The second is for the larger (currently) 3GB file.

**Comment by arm61** [comment]
Looks like it is working. Thanks!

**Comment by rodluger** [comment]
Great. Fixed in `v0.1.31`. Just run a `make update`.

**Comment by arm61** [comment]
This seems to be broken again...?

**Comment by rodluger** [comment]
Lol! No worries!
